// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ytxenngxwhmfwliabrwn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0eGVubmd4d2htZndsaWFicnduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMjM4ODUsImV4cCI6MjA2NzU5OTg4NX0.XeEZzO81RgwLtejMDmZICepc9_JTcMdcy6UW6oD9AzU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});